Repository derrick1451/ruby-capstone, pull requests merged in 2023-08, with the labels that each got.

#40 Feature/create main
  main.rb
  sql/schema_albums.sql
Labels: enhancement

#44 module4:Update book and label class
  book.rb
  label.rb
  schema.sql
Labels: enhancement

#49 Feature/preserve data
  .rubocop.yml
  app.rb
  lib/classes/album_collection.rb
  lib/classes/book.rb
  lib/classes/book_collection.rb
  lib/classes/item.rb
  lib/classes/music_album.rb
  lib/helpers/collection_handler.rb
  lib/helpers/json/albums.json
  lib/helpers/json/authors.json
  lib/helpers/json/books.json
  lib/helpers/json/genres.json
  lib/helpers/json/labels.json
  lib/helpers/preserve_data.rb
  main.rb
Labels: Preserve Data

#52 Preserve game
  lib/classes/game.rb
  lib/classes/game_collection.rb
  lib/helpers/collection_handler.rb
  lib/helpers/preserve_data.rb
Labels: enhancement

#53 added game_spec
  spec/game_spec.rb
Labels: Testing

#56 Develop
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .gitignore
  .rubocop.yml
  Gemfile
  Gemfile.lock
  LICENSE
  README.md
  app.rb
  lib/classes/album_collection.rb
  lib/classes/author.rb
  lib/classes/book.rb
  lib/classes/book_collection.rb
  lib/classes/game.rb
  lib/classes/game_collection.rb
  lib/classes/genre.rb
  lib/classes/item.rb
  lib/classes/label.rb
  lib/classes/music_album.rb
  lib/helpers/collection_handler.rb
  lib/helpers/json/albums.json
  lib/helpers/json/authors.json
  lib/helpers/json/books.json
  lib/helpers/json/games.json
  lib/helpers/json/genres.json
  lib/helpers/json/labels.json
  lib/helpers/preserve_data.rb
  main.rb
  spec/album_collection_spec.rb
  spec/album_spec.rb
  spec/author_spec.rb
  spec/book_spec.rb
  spec/game_spec.rb
  spec/genre_spec.rb
  spec/item_spec.rb
  spec/label_spec.rb
  sql/schema.sql
Labels: documentation, enhancement, db schema, Preserve Data, Testing
